# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ejohxCzZ18CXkVDeA2-4Em7aObwl-Rvw
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import calendar
# %matplotlib inline

data = pd.read_csv('data/convertcsv.csv', sep=';', parse_dates=['start', 'end', 'clean_end'])


print(data.head())
display(data)

format_dict = {'Mes':'{:%m-%Y}'}
data.head(10).style.background_gradient(cmap='BuGn')

data['region_title'].value_counts().plot(kind='pie', figsize=(6,6), label="")

data['start'].sort_values(ascending=True).map(lambda x: "%s %s %s"%(calendar.month_name[x.month], " ", x.year)).value_counts()[data.start.map(lambda x: "%s %s %s"%(calendar.month_name[x.month], " ", x.year)).unique()].plot(kind='bar', figsize=(14,6))

grouped = data.groupby(data['region_title'])
for name, group in grouped:
  plt.figure()
  group['ordinal'] = [x.date().toordinal() for x in group.start]
  ax = group['ordinal'].plot(kind='kde', figsize=(19,6), title=name)
  xlabels = [datetime.fromordinal(int(x)).strftime('%Y-%m-%d') for x in ax.get_xticks()]
  ax.set_xticklabels(xlabels)
  ax.axvline(group['ordinal'].mean(), color='red')
  ax.axvline(group['ordinal'].median(), color='green')
  plt.figure()
  group['start'].sort_values(ascending=True).map(lambda x: "%s %s %s"%(calendar.month_name[x.month], " ", x.year)).value_counts()[group.start.map(lambda x: "%s %s %s"%(calendar.month_name[x.month], " ", x.year)).unique()].plot(kind='bar', figsize=(20,6), title=name)