# Default values for mqttBroker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: "cool-app"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80